export const data = [{
    "name": "Family photo 1",
    "url": "/images/1.jpg",
    "description": "Photo 1 description",
    "date": "2023-02-10",
    "type": "image/jpg",
  },
  {
    "name": "Family photo 2",
    "url": "/images/2.jpg",
    "description": "Photo 2 description",
    "date": "2023-02-10",
    "type": "image/jpg",
  },
  {
    "name": "Family photo 3",
    "url": "/images/3.jpg",
    "description": "Photo 3 description",
    "date": "2023-02-10",
    "type": "image/jpg",
  },
  {
    "name": "Family photo 4",
    "url": "/images/4.jpg",
    "description": "Photo 4 description",
    "date": "2023-02-10",
    "type": "image/jpg",
  },
  {
    "name": "Family photo 5",
    "url": "/images/5.jpg",
    "description": "Photo 5 description",
    "date": "2023-02-10",
    "type": "image/jpg",
  },
  {
    "name": "Family photo 6",
    "url": "/images/6.jpg",
    "description": "Photo 6 description",
    "date": "2023-02-10",
    "type": "image/jpg",
  },
  {
    "name": "Family photo 7",
    "url": "/images/7.jpg",
    "description": "Photo 7 description",
    "date": "2023-02-10",
    "type": "image/jpg",
  },
  {
    "name": "Family photo 8",
    "url": "/images/8.jpg",
    "description": "Photo 8 description",
    "date": "2023-02-10",
    "type": "image/jpg",
  },
  {
    "name": "Family photo 9",
    "url": "/images/9.jpg",
    "description": "Photo 9 description",
    "date": "2023-02-10",
    "type": "image/jpg",
  }]